Add GetSessionId API
DCS-gRPC/rust-server pull request #158
Opened 2022-06-13 10:02 UTC by vivanov

An attempt to implement following issue: https://github.com/DCS-gRPC/rust-server/issues/143

2022-06-19 09:38 UTC, rkusa reviewed
Thanks for the PR, just two minor suggestions 👍  (and protolint wants something: https://github.com/DCS-gRPC/rust-server/runs/6860585828?check_suite_focus=true)

2022-06-19 09:38 UTC, rkusa commented on src/rpc/mission.rs
> +            let _result = self
I think the following can be removed
```suggestion
            self
```

2022-06-19 09:38 UTC, rkusa commented on protos/dcs/mission/v0/mission.proto
> +  // Returns value of the dcs_grpc_session_id flag or current unixtime if it's not set
Suggestion (basically fewer implementation details):
```suggestion
  // Returns an ID for the current session. The ID will change upon mission change or server restart.
```

2022-06-20 07:02 UTC, vivanov commented on src/rpc/mission.rs
> +            let _result = self
Good point, updated

2022-06-20 07:04 UTC, vivanov commented on protos/dcs/mission/v0/mission.proto
> +  // Returns value of the dcs_grpc_session_id flag or current unixtime if it's not set
Good point, updated

2022-06-28 16:55 UTC, rurounijones requested changes
@vivanov Thanks for the contribution and sorry for the delay in testing. As far as I can tell everything is hunky-dory so thank you very much.

Could you update the CHANGELOG.md to include your change and then I will merge

2022-06-30 03:25 UTC, rurounijones approved these changes

2022-06-30 03:25 UTC, merged