Add Transform to Weapon Export
DCS-gRPC/rust-server pull request #190
Opened 2022-10-08 15:46 UTC by YoloWingPixie

@rkusa 

Resubmitting after rebase.

Updated Weapon export to include transform.
Added necessary intermediate struct and impl to facilitate.
Updated common proto to provide Position/Orientation/Velocity

2022-10-08 17:42 UTC, rurounijones approved these changes

2022-10-08 17:43 UTC, rurounijones requested changes
Could you add your changes to the changelog. I thought they were there but they seem to have disappeared

2022-10-09 07:32 UTC, rurounijones approved these changes

2022-10-09 08:36 UTC, rkusa approved these changes
👍

2022-10-09 08:36 UTC, merged